// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcnlpgdathwgcprutluo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjbmxwZ2RhdGh3Z2NwcnV0bHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjA3OTcsImV4cCI6MjA1NTc5Njc5N30.AB3xOiBfCJTpBr4n91rkNQrqQ8CbaEGh_fm_urz4BcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);